#ifndef RHEA_AST_BUILDER_HPP
#define RHEA_AST_BUILDER_HPP

#include <memory>

#include "nodes.hpp"
#include "parse_tree_node.hpp"
#include "internal/builder.hpp"

/*
 * Builder for the Rhea intermediate AST. This converts the parse tree
 * generated by PEGTL into a much simplified and more abstract structure
 * intended to be passed to the type checker, declaration checker, and
 * code generator. This representation can also be serialized to serve as
 * a module object format.
 */
namespace rhea { namespace ast {
    // Build a Rhea AST out of the PEGTL modified parse tree.
    std::unique_ptr<ASTNode> build_ast(parser_node* node);
}}

#endif /* RHEA_AST_BUILDER_HPP */